### ISSUE TITLE
MFCMapi core library does not compile with VS 2022 17.10

### ISSUE THREAD

**Issue by syncimprov** [microsoft/mfcmapi#719]
Build errors:

```
core\smartview\block\blockT.h(39,34): error C2062: type 'WORD' unexpected
core\smartview\block\blockT.h(43,27): error C2062: type 'WORD' unexpected
core\smartview\block\blockT.h(44,32): error C2062: type 'WORD' unexpected
core\smartview\block\blockT.h(39,34): error C2062: type 'DWORD' unexpected
core\smartview\block\blockT.h(43,27): error C2062: type 'DWORD' unexpected
core\smartview\block\blockT.h(44,32): error C2062: type 'DWORD' unexpected
core\smartview\block\blockT.h(39,34): error C2062: type 'BYTE' unexpected
core\smartview\block\blockT.h(43,27): error C2062: type 'BYTE' unexpected
core\smartview\block\blockT.h(44,32): error C2062: type 'BYTE' unexpected
```

**Comment by stephenegriffin** [comment]
Works for me (tm).

Did you make sure to clone submodules?
`git clone --recursive https://github.com/microsoft/mfcmapi.git`

**Comment by stephenegriffin** [comment]
Just updated to 17.10 from 17.9 and now repro - sounds like a problem with VS, not the project, but I'll see what I can find

**Comment by syncimprov** [comment]
Thanks @stephenegriffin. Reported to VS Developer Community. They have reproduced it and are looking into it.

Here is the link:

https://developercommunity.visualstudio.com/t/Compiling-MFCMapi-after-upgrade-to-VS-20/10662946
